name: rerf
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.9.24=py38h06a4308_0
  - krb5=1.19.2=hac12032_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libcurl=7.84.0=h91b91d3_0
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnghttp2=1.46.0=hce63b2e_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1q=h7f8727e_0
  - pip=22.2.2=py38h06a4308_0
  - pycurl=7.45.1=py38h8f2d780_0
  - python=3.8.13=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=63.4.1=py38h06a4308_0
  - sqlite=3.39.3=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.12=h5eee18b_3
  - pip:
    - addict==2.4.0
    - asttokens==2.0.8
    - backcall==0.2.0
    - bidict==0.22.0
    - bitarray==2.6.0
    - bitstring==3.1.9
    - charset-normalizer==2.1.1
    - commonmark==0.9.1
    - contourpy==1.0.5
    - cycler==0.11.0
    - dearpygui==1.7.3
    - decorator==5.1.1
    - einops==0.5.0
    - executing==1.1.1
    - fonttools==4.37.4
    - idna==3.4
    - imageio==2.22.2
    - imageio-ffmpeg==0.4.7
    - ipdb==0.13.9
    - ipython==8.5.0
    - jedi==0.18.1
    - kiwisolver==1.4.4
    - lpips==0.1.4
    - matplotlib==3.6.1
    - matplotlib-inline==0.1.6
    - mmcv==1.6.2
    - ninja==1.10.2.4
    - numpy==1.23.4
    - packaging==21.3
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.2.0
    - prompt-toolkit==3.0.31
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pygments==2.13.0
    - pymcubes==0.1.2
    - pyparsing==3.0.9
    - pyqt5==5.15.7
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.0
    - python-dateutil==2.8.2
    - pytorch-msssim==0.2.1
    - pyyaml==6.0
    - requests==2.28.1
    - rich==12.6.0
    - scipy==1.9.3
    - six==1.16.0
    - stack-data==0.5.1
    - toml==0.10.2
    - tqdm==4.64.1
    - traitlets==5.5.0
    - trimesh==3.15.5
    - typing-extensions==4.4.0
    - urllib3==1.26.12
    - wcwidth==0.2.5
    - yapf==0.32.0
    - opencv-python==4.3.0.38
